Data Wrangling I 
Perform data preprocessing on an open-source dataset: 
• Import required libraries  
• Load dataset from web source  
• Handle missing values  
• Describe dataset (statistics, variables, dimensions)  
• Perform data type conversion  
• Convert categorical variables to numerical  
-------------------------------------------------------------------------------------------------------------------

Titanic dataset 
DATASET FEATURES - 11

survived - Shows whether the passenger survived or not

pclass - Passenger class (ticket type)
1 = Upper class (rich), 2 = Middle, 3 = Lower

sex - Gender of passenger (male/female)

age - Age of passenger in years

sibsp - Number of siblings or spouse traveling with passenger
Shows family relation onboard

parch - Number of parents or children traveling with passenger
Helps understand family size

fare - Ticket price paid by passenger
Higher fare usually means higher class

embarked - Port where passenger boarded the ship
C = Cherbourg, Q = Queenstown, S = Southampton

In [2]:
# Import required libraries 
import numpy as np
import pandas as pd

In [3]:
# Load dataset from web source  
data=pd.read_csv('titanic.csv')
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
print("Mean Age using numpy:", np.mean(data['Age'])) # usage of numpy

Mean Age using numpy: 29.69911764705882

In [5]:
print(data.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [7]:
# statistics
data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [8]:
print("Shape of data (rows, columns) : ",data.shape)
print("\nDimension: ",data.ndim)
print("\nTotal no of elements: ",data.size)
print("\nData types :\n",data.dtypes)

Shape of data (rows, columns) :  (891, 12)

Dimension:  2

Total no of elements:  10692

Data types :
 PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [9]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [10]:
data.duplicated().sum()

np.int64(0)

In [11]:
# handle missing values 
data['Age'] = data['Age'].fillna(data['Age'].mean())
# data['Age'] = data['Age'].fillna(np.mean(data['Age']))              # usage of numpy
data.drop('Cabin', axis=1, inplace=True)

data['Embarked'] = data['Embarked'].fillna(data['Embarked'].mode()[0])

In [12]:
data.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [13]:
# Perform data type conversion  
# survived, pclass, embarked are converted to category
data['Survived']=data['Survived'].astype('category')
data['Pclass']=data['Pclass'].astype('category')
data['Embarked']=data['Embarked'].astype('category')

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    category
 2   Pclass       891 non-null    category
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     891 non-null    category
dtypes: category(3), float64(2), int64(3), object(3)
memory usage: 58.8+ KB

In [18]:
# Convert categorical variables to numerical   (one hot encoding)
dataNew=pd.get_dummies(data,columns=['Sex','Embarked'],drop_first=True,dtype=int)
print(dataNew.head())

   PassengerId Survived Pclass  \
0            1        0      3
1            2        1      1
2            3        1      3
3            4        1      1
4            5        0      3

                                                Name   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris  22.0      1      0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0      1      0
2                             Heikkinen, Miss. Laina  26.0      0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0      1      0
4                           Allen, Mr. William Henry  35.0      0      0

             Ticket     Fare  Sex_male  Embarked_Q  Embarked_S
0         A/5 21171   7.2500         1           0           1
1          PC 17599  71.2833         0           0           0
2  STON/O2. 3101282   7.9250         0           0           1
3            113803  53.1000         0           0           1
4            373450   8.0500         1           0           1